# Generated by Django 3.2.16 on 2023-10-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_item', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
